sudo: required
language: groovy
jdk:
- oraclejdk8
services:
- postgresql
branches:
  only:
  - master
before_script:
- chmod +x grailsw
script: ./grailsw clean && ./grailsw refresh-dependencies && ./grailsw test-app --stacktrace
deploy:
  provider: heroku
  api_key:
    secure:
  app: etscheduler
  on:
    repo: Mulatusisay/etscheduler