
language: java
jdk:
  - oraclejdk7
 
script: ./grailsw refresh-dependencies
     && ./grailsw test-app
services:
- postgresql
branches:
  only:
  - master
before_script:
- chmod +x grailsw



  app: etscheduler
  on:
    repo: Mulatusisay/etscheduler
